FROM node:16-alpine

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN npm install --save-dev env-cmd

# add app
COPY . ./

# Expose port
EXPOSE 3000

# start app
CMD ["npm", "start"]
